### ISSUE TITLE
Potential Violation Detected

### ISSUE THREAD

**Issue by assignguard-support** [ifrycolorado/CSCI101-Create-Project#1]
Hey ifrycolorado!

This repository has been flagged as containing material which potentially infringes upon an academic copyright or an institution's academic integrity policies.

At your earliest convenience, please do one of the following:
  - disable public access to your repository see [repository access settings](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility)
  - remove any content could be in violation of copyright law
  - remove any content could be in violation of an institution's academic integrity policy

Please feel free to continue any discussion here. Thanks!

**Comment by ifrycolorado** [comment]
What organization/institution/individual has flagged this repo as infringing upon an academic copyright? This code was written by me, and any resources used in the creation of this code has been referenced within the repo. Without more specificity, I see no reason to comply. 

If this is an issue, please respond by Nov. 18th at 9:00 AM EST. Otherwise, this issue will be closed.
